### ISSUE TITLE
Could not figure out metis IDX width

### ISSUE THREAD

**Issue by Gweiqi** [UCL/hemelb#3]
Dear hemelb Users and Developers!

When I run to "Compile and Install (phase 2)", I get the following error：
CMake Error at /home/gwqsz/hemelb-v0.7/dependencies/parmetis/use.cmake:26 (message):
  Could not figure out metis IDX width
Call Stack (most recent call first):
  /home/gwqsz/hemelb-v0.7/dependencies/parmetis/use.cmake:29 (metis_type)
  /home/gwqsz/hemelb-v0.7/dependencies/Modules/HemeLbDependency.cmake:3 (include)
  cmake/dependencies.cmake:9 (hemelb_dependency)
  CMakeLists.txt:103 (include)

I am a beginner and this question has been bothering me for a long time and I am eager to get your help!
Many thanks,
Guo Weiqi

**Comment by rupertnash** [comment]
Do you have ParMETIS setup and is the cmake finding it correctly? (If so you will be able to see the variables `PARMETIS_INCLUDE_DIR` etc set)

**Comment by Gweiqi** [comment]
In this step：“Booststrap process (phase 1)”， compiler found the library ParMETIS，but when I run to "Compile and Install (phase 2)", I get the error.

**Comment by rupertnash** [comment]
Sorry - what are these phases you mention? HemeLB has no "bootstrap process". 

I appreciate that the `INSTALL` file in the top of the repository is out of date but it does roughly explain your choice of how to build HemeLB. You can do either:

1. super build (point CMake at the top-level CMakeLists.txt) which will attempt to download and build any dependencies it's missing 
2. code-only build (point CMake at `Code/CMakeLists.txt`)- in this case you are responsible for supplying the dependencies

**Comment by Gweiqi** [comment]
Thank you very much, I got the method from this web page：
http://hemelb.org.s3-website.eu-west-2.amazonaws.com/tutorials/installation/bootstrap/

**Comment by rupertnash** [comment]
OK - I don't know about those docs and the version of HemeLB you can download there. From your report above I can see that the version you're using isn't the one in this repo. I'm afraid there are a few different ones floating around, but I've not been actively working on the code for a few years until just recently.

I hope to make a release in the near future. Until then I suggest contacting the authors of that website for help.

**Comment by Gweiqi** [comment]
Ok,Thank you.I’ii  try to use the code in this  version.

**Comment by Gweiqi** [comment]
Dear Rupert Nash!
I've solved the last problem, I think it was a problem with the line in the file named "/home/gwqsz/hemelb-v0.7/dependencies/parmetis/use.cmake".

But When I run the example "bifurcation_hires", I get this error：
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

I am eager to get your help!
Many thanks,
Guo Weiqi
