### ISSUE TITLE
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD  with errorcode -1

### ISSUE THREAD

**Issue by Gweiqi** [UCL/hemelb#4]
Dear hemelb Users and Developers!
        When I run the example "bifurcation_hires", I get this error：
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

I am a beginner and this question has been bothering me for a long time and I am eager to get your help!
Many thanks,
Guo Weiqi

**Comment by rupertnash** [comment]
Can you post the whole log please? HemeLB will print an error message immediately before calling `MPI_Abort`.

**Comment by Gweiqi** [comment]
gwqsz@gwqsz:~/bin/bin$ mpirun -n 4 /home/gwqsz/bin/bin/hemelb -in /home/gwqsz/hemelb-v0.7/examples/bifurcation/bifurcation_hires/input.xml  -out /home/gwqsz/bin/bin/
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[Rank 0000000, 0.0s, mem: 0010864]: Output directory '/home/gwqsz/bin/bin/' already exists.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD 
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[Rank 0000000, 0.0s, mem: 0010816]: Output directory '/home/gwqsz/bin/bin/' already exists.
[Rank 0000000, 0.0s, mem: 0010872]: Output directory '/home/gwqsz/bin/bin/' already exists.
[Rank 0000000, 0.0s, mem: 0010776]: Output directory '/home/gwqsz/bin/bin/' already exists.

**Comment by rupertnash** [comment]
The last line tells you the problem: the output directory exists. HemeLB will refuse to overwrite existing results.
