### ISSUE TITLE
 Expected 'm', got 'lattice'

### ISSUE THREAD

**Issue by Gweiqi** [UCL/hemelb#5]
Dear hemelb  Developers!
When I run the example file, I get the following error： 
[Rank 0000000, 0.0s, mem: 0011876]: Invalid units for element /home/gwqsz/hemelb-v0.7/examples/bifurcation/bifurcation_hires/input.xml:/hemelbsettings(2)/inlets(21)/inlet(22)/position(30). Expected 'm', got 'lattice'
[Rank 0000001, 0.0s, mem: 0011912]: Invalid units for element /home/gwqsz/hemelb-v0.7/examples/bifurcation/bifurcation_hires/input.xml:/hemelbsettings(2)/inlets(21)/inlet(22)/position(30). Expected 'm', got 'lattice'
[Rank 0000002, 0.0s, mem: 0012376]: Invalid units for element /home/gwqsz/hemelb-v0.7/examples/bifurcation/bifurcation_hires/input.xml:/hemelbsettings(2)/inlets(21)/inlet(22)/position(30). Expected 'm', got 'lattice'
[Rank 0000003, 0.0s, mem: 0011892]: Invalid units for element /home/gwqsz/hemelb-v0.7/examples/bifurcation/bifurcation_hires/input.xml:/hemelbsettings(2)/inlets(21)/inlet(22)/position(30). Expected 'm', got 'lattice'
This is the example file for the site, I didn't change it. And when I tried to follow the error prompts to change the file, it created other errors.
I am eager to get your help!
Many thanks,
Guo Weiqi

**Comment by rupertnash** [comment]
Please contact the website authors. The tutorial and examples are not developed in this repository.

The error is somewhat tersely explaining that the units of the inlet position (on line 30) should be given in metres but are given in lattice units.
